### ISSUE TITLE
Board - poprawka

### ISSUE THREAD

**Issue by cieplinski-tobiasz** [maro512/Loop2#14]
byłoby miło Piotrze (jako, że pisałeś te klasę), gdybyś mógł przerobić winningLine aby zwracało Collection< Cell >, jeśli to możliwe, sporo by to ułatwiło przy renderowaniu

**Comment by pzjp** [comment]
Obecne `List<Tile>` to w szczególności `Collection<Tile>` a nawet `Collection<? extends Cell>`. Czy użycie ogólnego typu `Cell` jest aż tak ważne?

**Comment by cieplinski-tobiasz** [comment]
Właśnie cell jest tutaj kluczowy, pal sześć listę. Zmienna Collection< Cell> nie akceptuje typu collection< Tile>

**Comment by pzjp** [comment]
Może można zastąpić typ docelowy tym z "wildcardem"? Oczywiście wpisanie kilku Cell zamiast Tile to nie problem.

**Comment by cieplinski-tobiasz** [comment]
ok, nie znałem tego typu z wildcardem, teraz będzie ok
