### ISSUE TITLE
Kierunki płytek, punkt 0,0

### ISSUE THREAD

**Issue by maro512** [maro512/Loop2#8]
coś z tymi kierunkami jest nie tak, wzsystko jakby w odbiciu lustrzanym. Punkt 0,0 na sztywno nie wiem czy OK

**Comment by pzjp** [comment]
Punkt (0,0) jest tylko punktem odniesienia w modelu gry (i oczywiście pozwala umieścić płytki względem siebie - współrzędne całkowite można potem przeliczać na ekranowe dodając przesunięcie). Co do zasady współrzędne są oparte o "orientację informatyczną", czyli y rośnie do dołu (gdy idziemy na południe, a x rośnie w prawo. W standardowym układzie współrzędnych y rośnie do góry (na północ).  W praktyce, w trakcie gry można go przesuwać. W szczególności Board ma metody zwracające skrajne współrzędne planszy, które można wykorzystać.
**Wystarczy zawsze brać y z minusem przy każdym odwoływaniu się do współrzędnych na planszy.** Chyba, że to ja mam dodać tę zamianę do metod Boarda?

**Comment by pzjp** [comment]
Na razie można albo wyliczyć średnią max i min współrzędnych i tak robić przesunięcie (ja jakoś tak robiłem w moim desktopowym programie dawno temu), albo walnąć płytkę (0,0) na środek ekranu.

**Comment by pzjp** [comment]
Tymczasowo zmieniłem znak y w PlayState. Oczywiście w przyszłości mogę przerobić model, żeby używał drugiej orientacji, ale nie na jutro :)

**Comment by maro512** [comment]
Lepiej byłoby nie ustawiać na sztywno punktu 0,0 jako startowego, tylko pozwolić graczowi wybrać dowolny punkt.

**Comment by pzjp** [comment]
Tylko jak już damy możliwość przesuwania planszy, to nie będzie miało żadnego znaczenia. Po co ktoś miałby zaczynać od rogu ekranu? Dopóki nie można przesuwać, to taki ruch byłby albo głupi, albo złośliwy.
